/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as BorradoresRouteImport } from './routes/borradores'
import { Route as IndexRouteImport } from './routes/index'

const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const BorradoresRoute = BorradoresRouteImport.update({
  id: '/borradores',
  path: '/borradores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/borradores': typeof BorradoresRoute
  '/historial': typeof HistorialRoute
  '/nueva': typeof NuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/borradores': typeof BorradoresRoute
  '/historial': typeof HistorialRoute
  '/nueva': typeof NuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/borradores': typeof BorradoresRoute
  '/historial': typeof HistorialRoute
  '/nueva': typeof NuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/borradores' | '/historial' | '/nueva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/borradores' | '/historial' | '/nueva'
  id: '__root__' | '/' | '/borradores' | '/historial' | '/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BorradoresRoute: typeof BorradoresRoute
  HistorialRoute: typeof HistorialRoute
  NuevaRoute: typeof NuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borradores': {
      id: '/borradores'
      path: '/borradores'
      fullPath: '/borradores'
      preLoaderRoute: typeof BorradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BorradoresRoute: BorradoresRoute,
  HistorialRoute: HistorialRoute,
  NuevaRoute: NuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
